### ISSUE TITLE
[Compilation Error] Rive Unity package fails to compile in Unity 6000.5.0f1 due to obsolete GetInstanceID()

### ISSUE THREAD

**Issue by arenhansy** [rive-app/rive-unity#167]
### Submission checklist

- [x] I have confirmed the issue is present in the latest version of the Rive Unity package
- [x] I have searched the documentation and forums and could not find an answer
- [x] I have searched existing issues and this is not a duplicate

### Description

The Rive Unity package fails to compile immediately upon importing or upgrading the project to Unity 6000.5.0f1. 

Unity 6000.5 introduces a breaking change where `GetInstanceID()` is marked as an obsolete compile-time error as Unity transitions to the new `EntityId` system. The compiler blocks the build with an error message stating that `GetInstanceID()` on Assets should not be used. 

Please update the asset ID referencing system to be compatible with Unity 6000.5.0f1 and later.

### Previous working version

Unity 6000.4.10f1

### Rive Unity package version

0.4.3

### Unity version

6000.5.0f1

### Target platform

macOS

### Editor OS & version

macOS 26.5.1

**Comment by damzobridge** [comment]
Thanks for opening an issue. I'll let you know once we've addressed this!

**Comment by WaleedAmer** [comment]
I'm also dealing with this. We're looking to update to 6.5 asap 🙏

**Comment by Travisism** [comment]
Confirmed still a critical issue in 6000.5.2f1 as well

**Comment by ncthbrt** [comment]
It is a fairly trivial fix. I vendored our Rive package and replaced the use of ints in the Rive file cache with EntityId and everything appears nominal.

**Comment by damzobridge** [comment]
This should be addressed in `v0.4.4-canary.56` onwards. You can install it in the package manager with:

```
https://github.com/rive-app/rive-unity.git?path=package#v0.4.4-canary.56
```
