### ISSUE TITLE
Compiler error in Unity 6.4 with SRP 17.4.0

### ISSUE THREAD

**Issue by CalvinTeaching** [rive-app/rive-unity#151]
After upgrading from 6000.3.11f1 to 6000.4.0f1 and Scriptable Render Pipeline Core from 17.3.0 to 17.4.0 I'm receiving the following error:

Library\PackageCache\app.rive.rive-unity@5501c5f026f8\Runtime\Components\Public\RenderPipelines\URP\RenderPass.cs(81,30): error CS0115: 'RenderPass.Execute(ScriptableRenderContext, ref RenderingData)': no suitable method found to override

The following block contains the error, which I believe could probably be fixed by wrapping the whole block with #if !UNITY_6000_4_OR_NEWER, as it states that the method is obsolete, so I'm guessing Unity finally removed the method entirely. 

<img width="927" height="611" alt="Image" src="https://github.com/user-attachments/assets/60cdf62c-9af3-4ab8-85c2-663b4e20e49f" />

**Comment by damzobridge** [comment]
Hello! We have a fix for this coming soon. I also wanted to mention that the Rive plugin only officially supports LTS versions of Unity (to allow Unity's APIs to settle). It looks like you're now using Unity 6.4, which doesn't have an LTS version available yet.

Will let you know as soon as there's a canary version available with the fix.
